# General Settings
name: Николай Дубков
job_title: Веб-разработчик
email: nikolai@dubkov.xyz
description: Приветствую, @username! Я не могу рассказать о себе использовав только 160 символов гипертекста. Подробнее обо мне, можно узнать на моей домашней страничке.
avatar: https://avatars.mds.yandex.net/get-yapic/39727/1130000023618087-1543417897/islands-200
favicon: /favicon.ico
twitter_handler: your_handler
analytics_code: UA-XXXXXXX-2
disqus: dubkov

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/1371' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }

gems:
    - jekyll-emoji

# Modules Settings
show_categories: 1
show_tags: 0
show_mood: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
    path: ""
    type: "posts"
    values:
    comments: "false"

# Serving
url: "http://dubkov.xyz"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 3
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed