# Настройки
name: Николай Дубков
job_title: Веб-разработчик
email: nikolai@dubkov.xyz
description:
avatar:
favicon: /favicon.ico
twitter_handler: _dubkov
analytics_code: UA-XXXXXXX-2
disqus: dubkov

# Социальные профили
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'https://twitter.com/_dubkov' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/gitmaestro' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }

# Настройки модулей
show_categories: 1
show_tags: 1
show_mood: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Что входит в стандарт?
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Сервер и хостинг
url: ""
baseurl: ""

# Вложения
include: ["_pages"]

# Вывод
permalink: /:categories/:title.html
category_dir: categories

# Постраничная навигация
paginate: 5
paginate_path: "/page:num/"

# Конверсион
markdown: kramdown
excerpt_separator: <!--more-->

# Верстка
sass:
  sass_dir: assets/partials
  style: compressed
